# Generated by Django 5.2.1 on 2025-05-12 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Faturamento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Indicador')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição do Indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.IntegerField()),
                ('valor_jan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_fev', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_mar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_abr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_mai', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_jun', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_jul', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_ago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_set', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_out', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_nov', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_dez', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.tipofaturamento')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.tipoindicador')),
            ],
        ),
    ]
